apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployemntapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapplication
          image: harshanani1708/kubernetesappimage
          ports:
           - containerPort: 80
        
    
