apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: webapp
type: LoadBalancer
spec:
  selector:
    matchLabels:
      app: webapp
  ports:
    nodePort: 30102
    port: 8080
    targetPort: 80
  
